### PR TITLE
Influxdb support for location lookups

### PR DESCRIPTION
**Pull request by Solliet**
We have added endpoints for geolocation lookups and inserts in influx as part of EPL421.

### CODE REVIEW

**Comment by anyplaceucy** [comment]
Guys can we also check whether there is any "free" visual analytic interface can be tailored to the access scheme of Anyplace (e.g., use Grafana, Chronograf or the default InfluxDB UI) and allow each Anyplace user to see his own own IoT devices? If not, we have to create our own dashboards for registering/managing IoT devices. Please also clarify whether this registration/management is already provisioned by the JSON API ...

**Comment by anyplaceucy** [comment]
The objective is to have Anyplace 4.0 (with IoT backend integration) ready by early 2020.

**Comment by Solliet** [comment]
Closing in favor of #315

**Comment by Paschalis** [comment]
Good, I'll be merging #313 shortly.


Also, make sure to reply on this:
> Guys can we also check whether there is any "free" visual analytic interface can be tailored to the access scheme of Anyplace (e.g., use Grafana, Chronograf or the default InfluxDB UI) and allow each Anyplace user to see his own own IoT devices? If not, we have to create our own dashboards for registering/managing IoT devices. Please also clarify whether this registration/management is already provisioned by the JSON API ...

**Pull request closed without merging**
