### PR TITLE
Fix several warnings from LGTM

### PR DESCRIPTION
**Pull request by stweil**
See https://lgtm.com/projects/g/dmsl/anyplace/.

### CODE REVIEW

**Comment by stweil** [comment]
@Costantinos, maybe you could add LGTM as a continuous integration tool: https://lgtm.com/projects/g/dmsl/anyplace/ci/.

**Comment by anyplaceucy** [comment]
Very good idea indeed, thanks for the tip Stefan. We shall look at this soon.

**Comment by samlanning** [comment]
@stweil @Costantinos @anyplaceucy the commit `54e6277` here introduces a syntax error, and as a result doesn't correctly fix the missing variable declarations, you may want to look into that: https://lgtm.com/projects/g/dmsl/anyplace/rev/54e62770e9e246f31cb13ff032d47e6a98cc2010

(The automated code review can help prevent the mistakes like this in the future as @stweil has already mentioned)

**Comment by stweil** [comment]
And yes again, it might be worth to add LGTM as a CI tool to this project.

**Comment by stweil** [comment]
There are also several errors which I did not address in my pull request because they need someone who knows the code better: https://lgtm.com/projects/g/dmsl/anyplace/alerts/?mode=list&severity=error.

**Pull request merged**
